services:
  - type: web
    name: rag-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: "AIzaSyAGO5xxrt5DrQi6dl9PhyzJ6zkaOv1BZtI"
        sync: false
